---
- name: Create the Resource Group in the specified region
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
    - name: Create resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ region }}"
