---
- name: Create the Public IP Address
  hosts: localhost
  connection: local
  tasks:
   
    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group_name }}"
        allocation_method: Static
        name: "{{ win_public_ip_name }}"
      register: output_ip_address

    - name: Dump public IP for VM which will be created
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"

    - name: Set Stat for Ansible Controller
      set_stats:
        data: 
          azure_vm_public_ip: "{{ output_ip_address.state.ip_address }}"
        per_host: false

