---
- name: Create the Virtual Network Interface card
  hosts: localhost
  connection: local
  tasks:
  
    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        security_group: "{{ network_sec_group_name }}"
        ip_configurations:
          - name: ipconfig1
            public_ip_address_name: demo_public_ip
            primary: true
